### PR TITLE
Fix: #802 Back button from library toolbar fixed

### LINKED ISSUE #802: Back button from library toolbar skips a page in between
**Describe the bug**
As a user when I press the back button from the library header toolbar, it skips the page containing My Notes, My Bookmarks, My Downloads and Course Announcements. However when I press the system back button it doesn't skip. For more details check the gif below.

**To Reproduce**
1. Go to Library fragment from homepage(After login)
2. Click on any course present in the list
3. Go to Any options from My Notes, My Bookmarks, My Downloads and Course Announcements.
4. Click the top left corner toolbar back button of the page.
5. It skips the options page and goes to list of course page directly.

**Expected behavior**
The tool bar back button should not skip the options page.

**Screenshots**
Record-2020-05-18-16-39-30-7a48d

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |Oppo A9 2020|
|Android Version|Android Pie 9.0    |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by HaripriyaB**
Fixes #802 

Changes: Made the toolbar back button to follow the onBackPressed method

Screenshots for the change:
Record-2020-05-19-20-56-10-7a48d

### CODE REVIEW

File: app/src/main/java/com/codingblocks/cbonlineapp/library/LibraryActivity.kt [hunk 1]
```diff
@@ -19,6 +19,9 @@ class LibraryActivity : BaseCBActivity() {
         super.onCreate(savedInstanceState)
         setContentView(R.layout.activity_library)
         setToolbar(libraryToolbar)
+        libraryToolbar.setNavigationOnClickListener(){
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/library/LibraryActivity.kt]: Nit change
`setNavigationOnClickListener{`

**Review by aggarwalpulkit596 — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/codingblocks/cbonlineapp/library/LibraryActivity.kt (hunk 1 above)
Comment (HaripriyaB) [reply app/src/main/java/com/codingblocks/cbonlineapp/library/LibraryActivity.kt:22]: means? Can you elaborate?

Comment (HaripriyaB) [reply app/src/main/java/com/codingblocks/cbonlineapp/library/LibraryActivity.kt]: oh I got it. 👍

**Review by aggarwalpulkit596 — APPROVED** [review]

**Comment by HaripriyaB** [comment]
@aggarwalpulkit596 should I squash the commits?
