### PR TITLE
Used Space Progress issue fixed

### LINKED ISSUE #696: Storage space tracker doesn't show the occupied space
**Describe the bug**
The storage space tracker in settings page doesn't show the occupied space in red as shown in the key below it.

**To Reproduce**
1. Download any course 
2. Go to Settings page from the side nav bar
3. See the available storage shown grey even though there is occupied space.(See Screenshot)

**Expected behavior**
The storage tracker should show red according to the downloaded files size Vs available space.

**Screenshots**
Screenshot_2020-05-14-15-14-25-98_7a48d95313daa0d8bdbf7891041c354f

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |Oppo A9 2020|
|Android Version|Android Pie 9.0    |

### PR DESCRIPTION
**Pull request by hardik-dua**
Fixes #696 

Progress Bar was not showing the space used after downloading the videos from the courses. But now its fixed and I have tested it on 3 different devices. Its working awesome :)

Screenshots for the change:
Screenshot_2020-06-05-18-14-09-25

### CODE REVIEW

**Comment by hardik-dua** [comment]
@aggarwalpulkit596 Bhayia pls have a look whenever you are free.

File: app/src/main/java/com/codingblocks/cbonlineapp/settings/SettingsActivity.kt [hunk 1]
```diff
@@ -102,6 +99,10 @@ class SettingsActivity : BaseCBActivity() {
                 it
             ).readableFileSize()
         })
+        val usedSpace : Double = file?.let { folderSize(it) }!!.toDouble() / 1048576
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/settings/SettingsActivity.kt]: Can you not use `!!` operator

**Review by aggarwalpulkit596 — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/codingblocks/cbonlineapp/settings/SettingsActivity.kt (hunk 1 above)
Comment (hardik-dua) [reply app/src/main/java/com/codingblocks/cbonlineapp/settings/SettingsActivity.kt]: Ok will do this

**Comment by hardik-dua** [comment]
@aggarwalpulkit596 done the changes pls review once again the latest commit
