### PR TITLE
refactor: fixes to MVVM Architecture followed by the app

### LINKED ISSUE #178: Implement ViewModels for Course and Video Activities
**Describe the feature you'd like**
Implement View Models for Course And Video Activities with koin

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #178 

Changes:
- ViewModels for Course and Video Activity
- Updated all Null Assertions with Safe Calls
- Improved Resources

### CODE REVIEW

**Comment by adityastic** [comment]
@aggarwalpulkit596 have a look

**Comment by adityastic** [comment]
@aggarwalpulkit596 The Online API Services are not working. The Travis Failed, Please Check if the API's are up or not

File: app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt [hunk 1]
```diff
@@ -204,85 +212,100 @@ class CourseActivity : AppCompatActivity(), AnkoLogger {
...
-        Clients.onlineV2JsonApi.courseById(courseId).enqueue(retrofitCallback { t, resp ->
-            resp?.body()?.let { course ->
-                skeletonScreen.hide()
-                fetchInstructors(course.id)
-                batchAdapter = BatchesAdapter(ArrayList(), object : OnCartItemClickListener {
-                    override fun onItemClick(id: String, name: String) {
-                        addtocart(id, name)
+        viewModel.getCourse(object : OnCompleteCourseListener {
+            @Suppress("UNCHECKED_CAST")
+            override fun onCompleteJson(response: Response<JsonObject>) {
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt]: Don't use listeners/callback method use livedata instead see other viewmodels for reference

File: app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt [hunk 2]
```diff
@@ -204,85 +212,100 @@ class CourseActivity : AppCompatActivity(), AnkoLogger {
...
-                                if (response.isSuccessful) {
-                                    val value = response.body()!!
-                                    value.order = index
-                                    sectionsList.add(value)
-                                    if (sectionsList.size == sections.size) {
-                                        sectionsList.sortBy { it.order }
-                                        rvExpandableskeleton.hide()
-                                        sectionAdapter.setData(sectionsList)
+                    fetchTags(course)
+                    showPromoVideo(course.promoVideo)
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt]: Even this should be directly fetched from livedata value see MyCourseActitvity

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+                if ((response as Response<Notes>).isSuccessful)
+                    onVideoCompleteListener.onComplete(response as Response<JsonObject>)
+                else
+                    onVideoCompleteListener.onFailed()
+            })
+    }
+}
+
+interface OnVideoCompleteListener {
+    fun onComplete(response: Response<JsonObject>)
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: And why JsonObject obviously it won't work

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+import retrofit2.Response
+
+class VideoPlayerViewModel(
+    var doubtsDao: DoubtsDao,
+    var notesDao: NotesDao,
+    var courseDao: CourseDao,
+    var runDao: CourseRunDao
+) : ViewModel() {
+    lateinit var attemptId: String
+    lateinit var contentId: String
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: Move these variables to Activity

File: app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt (hunk 1 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt]: on it

File: app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt (hunk 2 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt]: let me push an update to this as well

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 3 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: removed

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 4 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: done

**Comment by adityastic** [comment]
@aggarwalpulkit596 updated CourseActivity, confirm if the changes are as per the requirement.

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 3 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: im updating the course activity, give your feedback on the changes. If it gets accepted I shall go on and perform the same on the Video Activity

**Comment by adityastic** [comment]
@aggarwalpulkit596 stacktrace to the failure:
`com.codingblocks.onlineapi.api.OnlineJsonApiPublicTest > GET recommended FAILED
    java.lang.AssertionError at OnlineJsonApiPublicTest.kt:30`

Please Confirm the issue with the public API

**Comment by aggarwalpulkit596** [comment]
> @aggarwalpulkit596 stacktrace to the failure:
> `com.codingblocks.onlineapi.api.OnlineJsonApiPublicTest > GET recommended FAILED java.lang.AssertionError at OnlineJsonApiPublicTest.kt:30`
> 
> Please Confirm the issue with the public API

Check Now

**Comment by adityastic** [comment]
@aggarwalpulkit596 fixed, check the CourseActivity. Let me know if you need any more changes in the approach

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 3 above)
Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: First of all they are Gson Response not Json Response and secondly it shouldn't be like that it should be at all you should save the dao here itself and if error show an error message using a boolean livedata variable and snackbar message

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: I didn't change the Video Activity as of now. I've updated only the Course Activity and it's ViewModel with the livedata and observers with the mutable boolean variables. I will make changes to the VideoClass once you confirm the refactor for One Class

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: Btw I don't get what you mean by Gson Response. It is a Retrofit Response of Gson JsonObject right?

Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: No it's GSON see client class in onlineapi. Module

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: @aggarwalpulkit596 Check this Sir.

The Call
Screenshot 2019-05-30 at 2 37 02 PM

The GSON JsonObject import
Screenshot 2019-05-30 at 2 37 10 PM

Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: Not every call is a JsonObject notes are of type GSON

Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: There are two different interfaces onlineRESTAPI and onlineJSONAPI so do your work accordingly

**Comment by adityastic** [comment]
@aggarwalpulkit596 I've updated both the activities. Thanks for the update

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+                            response?.body()?.content?.id ?: "",
+                            response?.body()?.runAttempt?.id ?: "",
+                            response?.body()?.createdAt ?: "",
+                            response?.body()?.deletedAt ?: ""
+                        )
+                    )
+                } catch (e: Exception) {
+                    getOtpProgress.value = false
+                }
+                getOtpProgress.value = (response?.isSuccessful == true)
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: otpProgress ?

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+            })
+    }
+
+    fun createNote(note: Notes) {
+        Clients.onlineV2JsonApi.createNote(note)
+            .enqueue(retrofitCallback { _, response ->
+                try {
+                    notesDao.insert(
+                        NotesModel(
+                            response?.body()?.id ?: "",
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: `use response?.body?.let {}`

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+                    )
+                )
+                createDoubtProgress.value = (response?.isSuccessful == true)
+            })
+    }
+
+    fun createNote(note: Notes) {
+        Clients.onlineV2JsonApi.createNote(note)
+            .enqueue(retrofitCallback { _, response ->
+                try {
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: why only notes are in try catch block and not others ?

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: It is because the original file had a try block in notes, and others didn't

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 6 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: Got it

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 5 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: Forgot to remove it after setting observer, thanks

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: Yes when response is received, we need to initialize the view. So it acts as a listener as you said

Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: how are notes related to otpProgress?

**Comment by adityastic** [comment]
@aggarwalpulkit596 updated, have a look if I am missing anything

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 5 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: Oh wait, my bad. I intialized the wrong variable. Updated, have a look

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 7 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: I've updated the rest dao operations as well :)

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+    }
+
+    fun createDoubt(doubt: DoubtsJsonApi) {
+        Clients.onlineV2JsonApi.createDoubt(doubt)
+            .enqueue(retrofitCallback { _, response ->
+                response?.body()?.let {
+                    if (response.isSuccessful) {
+                        doubtsDao.insert(
+                            DoubtsModel(
+                                doubt.id, doubt.title, doubt.body, doubt.contents?.id
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: it should be it.id as doubt.id is not auto-generated and is returned from the server.
Check the complete flow of the app make sure there is no crash/bug etc.

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: Yes as I'm using let, I should use it here. Let me test the complete app again to verify everything is working. Give me an hour to make sure it is not glitched

Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: No, it's not about using let here doubt.id would be null as while creating an object of doubt we don't have an id it is generated from server side and then we save it do our DB

Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: same goes for notes as well

Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: also refractor VideoDoubtsFragment and VideoNotesFragment and delete the singleton object of appdatabase and make sure appdatabase object is being no where and only koin is being used for accessing database
Don't worry I'll accommodate points accordingly

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: @aggrawalpulkit596, sounds great. This pr was very informative btw, thanks for having me here

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: @aggarwalpulkit596 tell me a course which has doubts or notes in it

Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: Notes and doubts are user created thing not a course specific thing

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: @aggarwalpulkit596 yes please name one course for me, I need to test them

Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: you can enroll in any course for trial and check the functionality

File: app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt [hunk 9]
```diff
@@ -48,51 +48,42 @@ class CourseDataAdapter(
 
     override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
 
-        var viewHolder: RecyclerView.ViewHolder? = null
+        var viewHolder: RecyclerView.ViewHolder = MyCoursesViewHolder(LayoutInflater.from(parent.context).inflate(R.layout.my_course_card_horizontal, parent, false))
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt]: Why . are you setting viewHolder even before knowing the type

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt]: when you know there are only two conditions, set the initial value as one and change it if it matches the other.

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt]: it is better than null asserting the viewholder which is a crucial component

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 8 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: @aggarwalpulkit596 great, let me try that

File: app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt (hunk 9 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt]: I've improved the condition, let me know if you agree

**Comment by adityastic** [comment]
@aggarwalpulkit596 wow, it was a fun day after all. Here are the changes :
- Created ViewModels for 6 Classes
- Removed Null Calls from all the changed classes
- Removed AppDatabase Instance 
- fixed explicit scoping for all classes
etc
Please have a look if I missed anything

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 7 above)
Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: i made some changes in this pr why had you removed them?

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: @aggarwalpulkit596 Must have occured because I force pushed the branch, can you suggest the changes again?

**Comment by adityastic** [comment]
@aggarwalpulkit596 updates on this plz

**Comment by aggarwalpulkit596** [comment]
Will take a look tomorrow till then you can do can open some more issues or work on other pending issues

**Comment by adityastic** [comment]
@aggarwalpulkit596 morning, sure take your time. I shall work on the other issues till then. Have a nice day

**Comment by adityastic** [comment]
@aggarwalpulkit596 please review

**Comment by aggarwalpulkit596** [comment]
Will update in an hour

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt (hunk 7 above)
Comment (aggarwalpulkit596) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt]: you're inserting notes and doubt irrespective of the response is successful or not it should be something like `if(response.isSuccesful)`

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/MyCourseViewModel.kt [hunk 10]
```diff
@@ -22,8 +22,8 @@ import com.codingblocks.onlineapi.Clients
 class MyCourseViewModel(
     var courseDao: CourseDao,
     var runDao: CourseRunDao,
-    private var sectionWithContentsDao: SectionWithContentsDao,
-    private var contentsDao: ContentDao,
+    var sectionWithContentsDao: SectionWithContentsDao,
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/MyCourseViewModel.kt]: why remove private from them

File: app/src/main/java/com/codingblocks/cbonlineapp/services/DownloadService.kt [hunk 11]
```diff
@@ -57,15 +58,13 @@ class DownloadService : IntentService("Download Service"), AnkoLogger,
...
-    private lateinit var database: AppDatabase
     private lateinit var contentDao: ContentDao
 
     override fun onHandleIntent(intent: Intent) {
         val title = intent.getStringExtra("title")
         dataId = intent.getStringExtra("id")
         notificationBuilder.setContentTitle(title)
-        database = AppDatabase.getInstance(this)
-        contentDao = database.contentDao()
+        contentDao = AppDatabase.getInstance(this).contentDao()
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/services/DownloadService.kt]: there should be not dependacy of AppDatabase anywhere
Infact i told you to delete the singleton object and use koin everywhere

File: app/src/main/java/com/codingblocks/cbonlineapp/fragments/VideoNotesFragment.kt [hunk 12]
```diff
@@ -57,77 +48,29 @@ class VideoNotesFragment : Fragment(), AnkoLogger {
...
+        view.notesRv.layoutManager = LinearLayoutManager(requireContext())
         view.notesRv.adapter = notesAdapter
-        val itemDecorator = DividerItemDecoration(context!!, DividerItemDecoration.VERTICAL)
-        itemDecorator.setDrawable(ContextCompat.getDrawable(context!!, R.drawable.divider)!!)
+        val itemDecorator = DividerItemDecoration(requireContext(), DividerItemDecoration.VERTICAL)
+        itemDecorator.setDrawable(requireContext().resources.getDrawable(R.drawable.divider))
         view.notesRv.addItemDecoration(itemDecorator)
 
-        notesDao.getNotes(param1!!).observer(this) {
+        viewModel.notesDao.getNotes(param1.toString()).observer(this) {
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/fragments/VideoNotesFragment.kt]: it should access it livedata variable and not notesDao 
If there are viewModels for fragment/activity use livedata or mutables variables dao  shouldn't be accessible to fragments/activites it should be a private member of viewmodel

File: app/src/main/java/com/codingblocks/cbonlineapp/fragments/VideoDoubtFragment.kt [hunk 13]
```diff
@@ -42,45 +33,23 @@ class VideoDoubtFragment : Fragment(), AnkoLogger {
...
+        view.doubtsRv.layoutManager = LinearLayoutManager(requireContext())
         view.doubtsRv.adapter = doubtsAdapter
-        val itemDecorator = DividerItemDecoration(context!!, DividerItemDecoration.VERTICAL)
-        itemDecorator.setDrawable(ContextCompat.getDrawable(context!!, R.drawable.divider)!!)
+        val itemDecorator = DividerItemDecoration(requireContext(), DividerItemDecoration.VERTICAL)
+        itemDecorator.setDrawable(requireContext().resources.getDrawable(R.drawable.divider))
         view.doubtsRv.addItemDecoration(itemDecorator)
-        doubtsDao.getDoubts(param1!!).observe(this, Observer<List<DoubtsModel>> {
+
+        viewModel.doubtsDao.getDoubts(param1.toString()).observe(this, Observer<List<DoubtsModel>> {
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/fragments/VideoDoubtFragment.kt]: use Observer extension and use live data variable not dao function

File: app/src/main/java/com/codingblocks/cbonlineapp/fragments/MyCoursesFragment.kt [hunk 14]
```diff
@@ -51,7 +51,8 @@ class MyCoursesFragment : Fragment(), AnkoLogger {
         courseDataAdapter =
             CourseDataAdapter(
                 ArrayList(),
-                activity!!,
+                viewModel.courseDao,
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/fragments/MyCoursesFragment.kt]: why this ?

File: app/src/main/java/com/codingblocks/cbonlineapp/fragments/AnnouncementsFragment.kt [hunk 15]
```diff
@@ -9,25 +9,27 @@ import androidx.lifecycle.Observer
...
     lateinit var courseId: String
     private lateinit var firebaseAnalytics: FirebaseAnalytics
 
+    private val viewModel by viewModel<AnnouncementsViewModel>()
+
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
         arguments?.let {
-            courseId = it.getString(ARG_COURSE_ID)!!
+            courseId = it.getString(ARG_COURSE_ID) ?: ""
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/fragments/AnnouncementsFragment.kt]: use variable from constant class

File: app/src/main/java/com/codingblocks/cbonlineapp/adapters/VideosDoubtsAdapter.kt [hunk 16]
```diff
@@ -168,10 +164,8 @@ class VideosDoubtsAdapter(private var doubtsData: ArrayList<DoubtsModel>) :
             doubts.id = doubt.dbtUid
             comment.doubt = doubts
             Clients.onlineV2JsonApi.createComment(comment)
-                .enqueue(retrofitCallback { throwable, response ->
-                    response?.body().let {
-                        notifyDataSetChanged()
-                    }
+                .enqueue(retrofitCallback { _, _ ->
+                    notifyDataSetChanged()
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/adapters/VideosDoubtsAdapter.kt]: notify only if the response is successful

File: app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionDetailsAdapter.kt [hunk 17]
```diff
@@ -420,11 +414,11 @@ class SectionDetailsAdapter(
                 })
         }
 
-        private fun connectedToWifi(context: Context): Boolean {
+        private fun connectedToWifi(context: Context): Boolean? {
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionDetailsAdapter.kt]: move this to utils

File: app/src/main/java/com/codingblocks/cbonlineapp/fragments/MyCoursesFragment.kt (hunk 14 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/fragments/MyCoursesFragment.kt]: You were passing the activity, that is never a good practise. Check the line below this, it is the best practise to use context in any fragment

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/fragments/MyCoursesFragment.kt]: And the dao. Because we were initializing the dao inside the adapter everytime a view was binding.

File: app/src/main/java/com/codingblocks/cbonlineapp/fragments/VideoNotesFragment.kt (hunk 12 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/fragments/VideoNotesFragment.kt]: Got it

File: app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/MyCourseViewModel.kt (hunk 10 above)
Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/MyCourseViewModel.kt]: because I did not take the mutable approach. I'm updating it as well as all the viewmodels to follow this

Comment (adityastic) [reply app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/MyCourseViewModel.kt]: because I passed them as parameters into the adapter, let me find the perfect way out

**Comment by adityastic** [comment]
@aggarwalpulkit596 I've Updated all the ViewModels. Please allot me bounty accordingly. Thanks

**Comment by aggarwalpulkit596** [comment]
Notes are not working

**Comment by aggarwalpulkit596** [comment]
Check Each and Every Activity/Fragment and add a video for the same

**Comment by adityastic** [comment]
@aggarwalpulkit596 is the doubts api not working?

**Comment by adityastic** [comment]
@aggarwalpulkit596 https://drive.google.com/file/d/1-74XapXg_Fs3bVFdX10LovOtqvVqgXKJ/view?usp=drivesdk

**Comment by adityastic** [comment]
@aggarwalpulkit596 please have a look

**Comment by adityastic** [comment]
@aggarwalpulkit596 I've updated the PR, changed the null assertions in shortcuts.

**Comment by aggarwalpulkit596** [comment]
Why are you making changes which are not required in this PR i wouldn't be giving you any extra points for this and will not accept any PR in future if any unnecessary changes are made

**Comment by adityastic** [comment]
@aggarwalpulkit596 It was causing merge conflicts as the shorcuts are created in HomeActivity and I made changes to it

**Comment by adityastic** [comment]
@aggarwalpulkit596 I can understand this PR is so big already, If you want I can seperate this into multiple PR's so we can target one part of the application at a time and it would release the load from you as well. Let me know your thoughts on this

**Comment by aggarwalpulkit596** [comment]
No issues i will merge this one today positively but for future don't do changes which are not related to this pr i specifically told you not convert all the classes to viewmodels and still you did that no issues it's a good thing but a author it's makes my work more and more difficult to check the complete PR probably i will miss few things in this PR which i have to fix myself

**Comment by adityastic** [comment]
@aggarwalpulkit596 You can always find me here if there is any issue hindering this pr. I shall be available whenever you need me

**Comment by aggarwalpulkit596** [comment]
In Some Adapter, you have passed viewmodel object where as in some adapters you're passing dao object use one of them only and also instead of toString use elvis operator  `? : ""`

**Comment by aggarwalpulkit596** [comment]
Rest Looks Good To Me Although there are some irrelevant changes in the PR 1500 points would be sufficient i guess
Points are not proportional to amount to work as there 1000+ lines but it is actually the amount of actual productive work/ adding a new feature fixing a bug etc so 1500 would be fine

**Comment by adityastic** [comment]
@aggarwalpulkit596 Yes I completely agree, productivity is never proportional to LOC, I appreciate the extra 500. Thank you so much 😆

**Comment by adityastic** [comment]
@aggarwalpulkit596 regarding the adapter with dao object. It is specifically with the `CourseDataAdapter` because it is being called by 3 fragments, that led to conflicts in defining the viewModel Type, If you want I can force cast them inside the adapter accordingly. Let me know your thoughts on this. And let me update the elvis operator with toString() wherever possible

**Comment by aggarwalpulkit596** [comment]
Why there is a courseDao Object in CourseDataAdapter it wasn't there before

File: app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt [hunk 18]
```diff
@@ -47,107 +39,18 @@ class CourseDataAdapter(
...
-
-    inner class AllCoursesViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
-
-        private lateinit var courseDao: CourseDao
-        private lateinit var database: AppDatabase
-
-        fun bindView(courseRun: CourseRun, courseWithInstructorDao: CourseWithInstructorDao, context: Context) {
-
-            database = AppDatabase.getInstance(context)
-            courseDao = database.courseDao()
```
Comment (adityastic) [inline app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt]: This is why @aggarwalpulkit596

**Comment by adityastic** [comment]
@aggarwalpulkit596 I've Claimed 1500 points for this as well. Please accept the claim in your free time
Regards 😄

**Comment by adityastic** [comment]
@aggarwalpulkit596 bounty allotted to me for this pr is 1250 and not 1500. can you please check, I remember claiming 1500 only

**Comment by aggarwalpulkit596** [comment]
Yes i deducted 250 points for some reason i don't remember exactly why

**Comment by adityastic** [comment]
> Yes i deducted 250 points for some reason i don't remember exactly why

Is there any way I can try to make up for them?

**Comment by aggarwalpulkit596** [comment]
Well, Now you can't as you can't raise a claim on the website anymore

**Comment by adityastic** [comment]
> Well, Now you can't as you can't raise a claim on the website anymore

anything other than making a claim, can you not change it and let me fix it here?
