### PR TITLE
[FIX] Quiz Backstack 

### LINKED ISSUE #632: [BUG] Quiz info Fragment attached with No Details
**Describe the bug**
When the user starts the quiz from the curriculum, as expected it goes Quiz Activity. Here Quiz Info fragment gets attached where the user starts the quiz by clicking **START QUIZ** button.  Once the user goes to the 1st question fragment and then press back, Quiz Info fragment gets attached with no details.

**To Reproduce**

1. Go to **Any Quiz**
2. Click on **START QUIZ**
3. Press Back  
4. You will get back to the info fragment with no details.

**Expected behavior**
Alert Dialog should be Popup for asking "Are you sure you want to exit from quiz" 

**Screenshots**
gif

**Smartphone Info:**

|Device         | **Realme XT**|
|Android Version| android 10  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by iamspathan**
Fixes #632 
Changes:Replace FragmentPagerAdapter with FragmentStatePagerAdapter and ParentFragmentManager with ChildFragmentManager

### CODE REVIEW

File: app/src/main/java/com/codingblocks/cbonlineapp/mycourse/quiz/QuizResultFragment.kt [hunk 1]
```diff
@@ -10,9 +10,13 @@ import android.view.ViewGroup
 import com.codingblocks.cbonlineapp.R
 import com.codingblocks.cbonlineapp.baseclasses.BaseCBFragment
 import com.codingblocks.cbonlineapp.util.extensions.replaceFragmentSafely
+import com.codingblocks.onlineapi.Clients
 import kotlinx.android.synthetic.main.fragment_quiz_result.*
+import kotlinx.coroutines.*
 
-class QuizResultFragment : BaseCBFragment() {
+class QuizResultFragment(val quizAttemptId: String) : BaseCBFragment() {
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/mycourse/quiz/QuizResultFragment.kt]: use newInstance to pass quizId

**Review by aggarwalpulkit596 — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/codingblocks/cbonlineapp/mycourse/quiz/QuizResultFragment.kt (hunk 1 above)
Comment (iamspathan) [reply app/src/main/java/com/codingblocks/cbonlineapp/mycourse/quiz/QuizResultFragment.kt]: Okay

**Review by aggarwalpulkit596 — APPROVED** [review]
