### PR TITLE
fix: WhatsApp card displaying for empty link

### LINKED ISSUE #720: Join Whatsapp Group section shows 'Install Whatsapp'
**Describe the bug**
I wanted to join the whatsapp group for my course, but after clicking on it, it shows 'Please Install Whatsapp'. Even if the course group doesn't exist , we could redirect students to a group or a number where they could know about upcoming courses .

**To Reproduce**
1. Go to your purchased course
2. Click on continue learning.
3. Scroll down to Join Group
4. See error --> Please install whatsapp

**Expected behavior**
It should redirect to a whatsapp group .

**Screenshots**

image

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |[Oppo A3s]   |
|Android Version|[Oreo 8.1]    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by Dhruv-194**
Fixes #720 

Changes: I created an if else condition which checks whether the desired course has an intended 'WhatsApp Group' link, if the link is non empty or not null then only the 'WhatsApp Card to join Group' is displayed otherwise it does not. Hence you do not get the Toast Message saying "Please join WhatsApp". 
This ensures that the card is displayed only for those course which has 'WhatsApp Group' and an active link for joining it.

Screenshots for the change:
Screenshot_20200519-035210

(for the same 'course' in the 'issue screenshot' the card was getting displayed, but in this no card is getting displayed because this course does not have a WhatsApp group)

### CODE REVIEW

File: app/src/main/java/com/codingblocks/cbonlineapp/mycourse/overview/OverviewFragment.kt [hunk 1]
```diff
@@ -148,16 +149,20 @@ class OverviewFragment : BaseCBFragment(), AnkoLogger {
...
-            isVisible = premium
-            setOnClickListener {
-                val intent = Intent(Intent.ACTION_VIEW)
-                intent.setPackage("com.whatsapp")
-                intent.data = Uri.parse(link)
-                if (requireContext().packageManager.resolveActivity(intent, 0) != null) {
-                    startActivity(intent)
-                } else {
-                    Toast.makeText(requireContext(), "Please install whatsApp", Toast.LENGTH_SHORT).show()
+        if (link.isNullOrEmpty()) {
```
Comment (aggarwalpulkit596) [inline app/src/main/java/com/codingblocks/cbonlineapp/mycourse/overview/OverviewFragment.kt]: Can you move this check to above where this function is being called

**Review by aggarwalpulkit596 — APPROVED** [review]
